# Generated by Django 4.0 on 2021-12-28 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('furigana', models.CharField(max_length=100, verbose_name='名前（フリガナ）')),
                ('tel_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='性別')),
                ('blood_type', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性'), (3, 'その他')], null=True, verbose_name='血液型')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('belong', models.CharField(max_length=100, verbose_name='所属')),
            ],
            options={
                'verbose_name_plural': 'Person',
            },
        ),
    ]
