# Generated by Django 4.0 on 2021-12-28 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood_type',
            field=models.IntegerField(blank=True, choices=[(1, 'A型'), (2, 'B型'), (3, 'O型'), (4, 'AB型')], null=True, verbose_name='血液型'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
