# Generated by Django 4.0 on 2021-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0003_alter_person_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='メールアドレス'),
        ),
    ]
