# Generated by Django 4.0 on 2021-12-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0004_alter_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tel_number',
            new_name='tel',
        ),
    ]
