# Generated by Django 4.0 on 2021-12-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0005_rename_tel_number_person_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tel',
            new_name='tel_number',
        ),
    ]
